### ISSUE TITLE
would be cool to use releases and semantic versioning

### ISSUE THREAD

**Issue by dfuentes77** [xor-gate/goexif2#8]
This is so that when using a dependency manager, we can lock to a version and get predictable builds

Otherwise, we're sticking to a commit sha or always pulling master.

For example, using [glide](http://glide.sh/), we can set it to only pull certain patch/minor versions based on our comfort.

**Comment by xor-gate** [comment]
Thats a good idea, I have tagged v1.0.0 now. This can be parsed with https://github.com/Masterminds/semver which is used by glide.

**Comment by dfuentes77** [comment]
Awesome, thanks!
